

import {Dancing_Script} from 'next/font/google'
import Image from 'next/image';
import Link from 'next/link';
import React from 'react'

const url =
  "https://free-to-play-games-database.p.rapidapi.com/api/games?category=pixel";
const options = {
  method: "GET",
  headers: {
    "X-RapidAPI-Key": "ac57dbe144msh1b7cf41ae3ff422p17282djsna199af6985d3",
    "X-RapidAPI-Host": "free-to-play-games-database.p.rapidapi.com",

  },
  
  
};
export const metadata = {
  title: "product",
  description: "Generated by create next app",
};
 async function getgame(){
    let data= await fetch(url,{
      // cache:'no-cache'
      next:{
        //every time in second make fetch
        revalidate:1
      },

      ...options})
    return await data.json()

 }
 const dancefont=Dancing_Script({
  subsets:['latin'],
  weight:"700"
})
export default async function poduct() {
    let data= await getgame()
    // in font use const not let
    
    
   
  return (
    <div className="container">
      <div className="row">
        {data.map((item)=>{
          return(
            <div class="col-lg-3 g-3 col-md-6 col-sm-6">
            <div  class="card  h-100 " >
              <Link href={`/product/${item.id}`}>
                <img width={250} height={250} class="card-img-top"  src={item.thumbnail} alt="Card image cap"/></Link>
              <div class="card-body">
                <h5 class={dancefont.className +" "+"card-title"}>${item.title}</h5>
                <p className={ "card-text   overflow-hidden"}>{item.short_description.slice(0,30)}</p>
                <div class="d-flex justify-content-between border-top fw-bolder">
                <p>${item.platform}</p>
                <p>${item.genre}</p>
                </div>
                
               <Link href={`/product/${item.id}`}> <a  data-id={item.id} class="btn buttondetails btn-primary">open details</a></Link>
              </div>
            
           
          </div>
          
          </div>


          )


        })}
      </div>


    </div>
  )
}
