import React from 'react'
export const metadata = {
  title: "brand",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div>
      <h1>brand</h1>
    </div>
  )
}
